/**
 * What a client is told about a coaching recommendation.
 *
 * Deliberately plain display data. The engine's Action object is *not* part of
 * this contract: the coach advises, the player still makes the move through
 * the normal action API, and nothing a reasoning layer produced can arrive at
 * the server as something to dispatch.
 *
 * Every string here is generated from the requesting player's own view of the
 * board, so it carries nothing their opponent's hand, deck or prizes.
 */
export interface CoachAdviceOption {
  /** What the move is, generated by the engine. Trustworthy. */
  description: string;
  /** Why it is suggested. May come from a reasoning layer. */
  rationale: string;
}

export interface CoachAdvice extends CoachAdviceOption {
  /** Whether the player is choosing a turn action or answering a prompt. */
  kind: 'turn-action' | 'prompt-response';
  /** The question being answered, when this is a prompt response. */
  question: string | null;
  /** Other legal options, best first. */
  alternatives: CoachAdviceOption[];
}
